### ISSUE TITLE
Full Stack projektin katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [hannuee/GenericStoreBackend#1]
# Full Stack projektin katselmointi

Terve @hannuee! Tässä lyhyt katselmointi Full Stack kurssin projektistasi. Katselmoinnissa esitetyt kommentit ovat parannusehdotuksia, joita voit _halutessasi_ ottaa huomioon tässä tai tulevissa projekteissasi. Mitään muutoksia tähän projektiin ei siis ole pakko tehdä suoritusmerkintää varten.

### Mitä tein?

- Selailin verkkokauppaa kirjautumattomana
- Yritin rekisteröityä siinä onnistumatta
- Kirjauduin sisään asiakkaana
- Lisäsin tuotteita ostoskoriin
- Yritin tehdä tilauksen, mutta se epäonnistui
- Kirjauduin sisään adminina
- Lisäsin kategorioita ja tuotteita
- Kirjauduin ulos

### Kokemus

- Verkkokaupalla on selkeä käyttöliittymä, hyvää työtä! 🏆
- Geneerisen "React App"-faviconin voisi muuttaa kuvaavammaksi
- Salasana-kentissä voisi käyttää `<input type="password" />` elementtiä
- Virheellisessä rekisteröitymisessä tulee vain virheviesti "Rekisteröityminen epäonnistui", eikä mitään tarkempaa tietoa virheestä. En löytänyt missä oli vika, joten jätin rekisteröitymisen kesken
- Lisäsin pari tuotetta ostoskoriin ja yritin lähettää tilauksen. Lopputuloksena oli virheviesti "Database error"
- Ainoastaan sovelluksen juuripolku (https://linnakauppa.herokuapp.com) aukeaa suoraan selaimessa, mutta esimerkiksi https://linnakauppa.herokuapp.com/kategoriat/1 avaaminen palauttaa virheviestin `unknown endpoint`. Syynä on luultavasti, se että frontendin index.html-tiedosto tarjoillaan backendin puolella vaan `/`-polusta. Esim. [tästä](https://gist.github.com/ryanoglesby08/1e1f49d87ae8ab2cabf45623fc36a7fe) Gististä voi saada vinkkejä ongelman korjaamiseen

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä! Hakemistossa `components` olevat komponentit kuulostaisivat sivuilta, ehkä hakemiston nimi voisi olla `pages` ja `assistingComponents` pelkkä `components`
- API-kutsut on abstraktoitu hyvin uudellenkäytettäviksi palveluiksi `services`-hakemistoon
- Muuttujat saa merkkijonoihin myös [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)-syntaksilla: `baseUrl + '/details/' + id` vs. <code>\`${baseUrl}/details/${id}\`</code>
- API-kutsuihin liittyvät operaatiot tuottavat Reduxin kanssa usein jonkin verran toisteellista boilerplate-koodia. Esimerkiksi [React Query](https://react-query.tanstack.com/) kirjaston avulla API-kutsut voi helposti abstraktoida yksinkertaisiksi hookeiksi
- Lomakkeiden tilanhallinta on hoidettu melko siististi, mutta kun lomakkeen koko kasvaa tai sen logiikka monimutkaistuu, on usein kätevää käyttää jotain lomakkeen tilanhallinnasta vastaavaa kirjastoa, kuten [Formik](https://jaredpalmer.com/formik)
- Voisiko [ostoskorin aloitustilan](https://github.com/hannuee/GenericStore/blob/main/genericstore/src/App.js#L28) lukea local storagesta suoraan [reducerissa](https://github.com/hannuee/GenericStore/blob/main/genericstore/src/reducers/orderReducer.js#L11)?
- Reduxin actioneiden typet kannattaa tallentaa `const`-tyyppisiin vakiomuuttujiin ja hyödyntää näitä muuttujia esim. reducereissa sen sijaan, että käyttäisi niitä suoraan [merkkijonomuotoisena](https://github.com/hannuee/GenericStore/blob/main/genericstore/src/reducers/categoryReducer.js#L5):

  ```javascript
  const ADD_TODO = 'todos/addTodo';

  // ...

  const todosReducer = (state, action) => {
    switch (action.type) {
      case ADD_TODO:
      // ...
    }
  };
  ```

  Tämä ehkäisee esimerkiksi kirjoitusvirheistä syntyviä bugeja ja helpottaa refaktorointia. Mallia voi katsoa Reduxin [dokumentaatiosta](https://redux.js.org/usage/reducing-boilerplate)

- Reduxin actioneita kannattaa luoda niin kutsuttujen [action creator](https://redux.js.org/usage/reducing-boilerplate)-funktioiden avulla sen sijaan, että käyttäisi suoraan [objekteja](https://github.com/hannuee/GenericStore/blob/main/genericstore/src/reducers/categoryReducer.js#L23) `dispatch`-kutsujen yhteydessä:

  ```javascript
  const ADD_TODO = 'todos/addTodo';

  const addTodo = (todo) => {
    return { type: ADD_TODO, payload: todo };
  };

  // jossain muualla koodissa...
  dispatch(addTodo('Create a cool React app'));
  ```

  Kun actionin luonti on abstraktoitu funktion avulla, sitä on helpompi muuttaa tulevaisuudessa ilman suurempaa refaktorointia

- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- SQL-tietokannan skeemaan määrittely kannattaa hoitaa [migraatioiden](https://knexjs.org/#Migrations) avulla. Eräs hyvä migraatiotyökalu ja SQL query builderi on [Knex](https://knexjs.org/)
- SQL-kyselyiden tekemistä [kontrollereissa](https://github.com/hannuee/GenericStoreBackend/blob/main/controllers/categories.js#L9) kannattaa välttää. Toteuta sen sijaan tietokantakyselyitä tekeviä apufunktioita, kuten `getCategories` ja käytä niitä kontrollereissa
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla
- Tietokantakyselyissä [tapahtuvat virheet](https://github.com/hannuee/GenericStoreBackend/blob/main/controllers/categories.js#L54) kannattaisi vähintään logittaaa `console.log(error)` avulla. Nyt tapahtuneesta virheestä ei jää jäljelle kuin "Database error"-virheviesti
- Hyviä uudelleenkäytettäviä middlewareja

## Kokonaisuus

Sovellus tarjoaa verkkokaupan perustoiminallisuuden, vaikkakin käyttökokemus on paikoitellen hieman buginen. Projektin koodi on kaikilta puolin järkevästi organisoitua ja kohtalaisen laadukasta. Esim. backendin puolella SQL-skeeman määrityksessä kannattaisia hyödyntää migraatioita ja kontrollereiden SQL-kyselyt kannattaisi abstraktoida uudelleenkäytettäviksi apufunktioitiksi. Kokonaisuudessaan kuitenkin hyvää työtä!

**Comment by hannuee** [comment]
Kiitos perusteellisesta ja hyvästä palautteesta :) 👍
